version: "2"
services:
  app:
    build: .
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      - MYSQL_DATABASE=dictionary
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
